all: compil clean

compil:
	pdflatex -shell-escape tp.tex
	pdflatex -shell-escape tp.tex

clean:
	rm -f tp.aux
	rm -f tp.fdb_latexmk
	rm -f tp.log
	rm -f tp.nav
	rm -f tp.out
	rm -f tp.snm
	rm -f tp.synctex.gz
	rm -f tp.toc
	rm -f tp.pyg
