all: compil clean

compil:
	pdflatex -shell-escape qcm.tex
	pdflatex -shell-escape qcm.tex

clean:
	rm -f qcm.aux
	rm -f qcm.fdb_latexmk
	rm -f qcm.log
	rm -f qcm.nav
	rm -f qcm.out
	rm -f qcm.snm
	rm -f qcm.synctex.gz
	rm -f qcm.toc
	rm -f qcm.pyg