@startuml

' Use http://www.planttext.com/planttext to compile

!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
!define variableType(x) <font color="#73AE42">x</font>
!define embed(x) <font color="#e67e22">x</font>
!define embed2(x) <font color="#e74c3c">x</font>
hide methods
hide stereotypes

skinparam shadowing false
skinparam stereotypeCBackgroundColor #5B9BD5

skinparam note {
  BackgroundColor #73AE42
  BorderColor #6CA43E
  FontColor white
}

skinparam class {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #FFFFFF
}

skinparam sequence {
  ArrowColor #6CA43E

  LifeLineBorderColor #6CA43E
  LifeLineBackgroundColor #73AE42

  ParticipantBorderColor #2E75B5
  ParticipantBackgroundColor #5B9BD5

  ActorBorderColor #2E75B5
  ActorBackgroundColor #5B9BD5

  BoxLineColor #A5A5A5
}

skinparam state {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #9E9E9E
}

skinparam usecase {
  BackgroundColor #EEEEEE
  BorderColor #9E9E9E

  ArrowColor #6CA43E
  ActorBorderColor #6CA43E
}

skinparam component {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #9E9E9E
}

skinparam node {
  BackgroundColor #FFFFFF
  ArrowColor #758A9F
  BorderColor #9E9E9E
}

skinparam database {
  BackgroundColor #EEEEEE
  ArrowColor #758A9F
  BorderColor #9E9E9E
}

table(recipes) {
  variableType(int) primary_key(id)
  variableType(string) title
  variableType(int) rating
  variableType(int) cookingTime
  variableType(int) preparationTime
  variableType(string) type
  variableType(string) slug
  variableType(string) description
  variableType(string) embed(ingredient).name
  variableType(string) embed(ingredient).unit
  variableType(float) embed(ingredient).price
  variableType(float) embed(ingredient).embed2(quantity).quantity
}

table(locations) {
  variableType(int) primary_key(id)
  variableType(string) date
  variableType(string) name
  variableType(string) description
  variableType(string) type
}

table(guests) {
  variableType(int) primary_key(id)
  variableType(string) name
  variableType(string) type
  variableType(string) phoneNumber
  variableType(boolean) embed(invite).toInvite
  variableType(int) embed(invite).numberOfInvitations
  variableType(date) embed(invite).lastInvite
}

table(events) {
  variableType(int) primary_key(id)
  variableType(string) name
  variableType(string) type
  variableType(string) date
}

recipes "0..n" o-- "1" locations
events "0..n " --- "0..m" guests
events "0..n" --- "0..m " recipes

@enduml
